# Use root/example as user/password credentials
version: "3.1"

services:
  postgres-local:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: JPA-TEST

    ports:
      - 5432:5432

    volumes:
      - ./data:/var/lib/postgresql/data
